name: Upstash Keep Alive

on:
  schedule:
    
    - cron: "17 0 */3 * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Upstash Redis
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
        run: |
          set -euo pipefail

          if [ -z "${UPSTASH_REDIS_REST_URL:-}" ] || [ -z "${UPSTASH_REDIS_REST_TOKEN:-}" ]; then
            echo "Missing secrets UPSTASH_REDIS_REST_URL or UPSTASH_REDIS_REST_TOKEN"
            exit 1
          fi

          echo "Pinging Upstash..."
          # Upstash Redis REST：POST /ping
          resp=$(curl -sS -X POST "${UPSTASH_REDIS_REST_URL}/ping" \
            -H "Authorization: Bearer ${UPSTASH_REDIS_REST_TOKEN}")

          echo "Response: $resp"
          # 预期包含：PONG
          echo "$resp" | grep -q "PONG"
